# config/database.yml
default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV['DB_USERNAME'] || 'postgres' %>
  password: <%= ENV['DB_PASSWORD'] || 'password' %>
  host: <%= ENV['DB_HOST'] || 'localhost' %>

development:
  <<: *default
  database: identity_provider_development

test:
  <<: *default
  database: identity_provider_test

production:
  <<: *default
  database: identity_provider_production
  username: identity_provider
  password: <%= ENV["IDENTITY_PROVIDER_DATABASE_PASSWORD"] %>